# Site settings
title: Seli Purnianda
description: '<p>Mahasiswa Sistem informasi TA 2014</p>
               <p>Fakultas : Sains dan Teknologi</p>
               <p>Universitas  Islam Negeri Sultan Syarif Kasim Riau</p>'
url: 'http://selipurnianda.github.io'
baseurl: '/selipurnianda.github.io/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Seli Purnianda'
  email: selipurnianda@gmail.com
  twitter_username: spurnianda
  facebook_username: seli purnianda
  github_username: selipurnianda
  linkedin_username: selipurnianda
  uin suska: http://uin-suska.ac.id/
  sif uin: http://sif.uin-suska.ac.id/


defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
